name: IPKick
version: 1
author: mclarence
main: xyz.mclarence.ipkick.IpKick
api-version: 1.14
commands:
  ipkick:
    description: Ipkick base command.
    usage: /ipkick
    permission: ipkick.base
    permission-message: You do not have access to this command.
